stages:
  data-ingestion:
    cmd: python -m src.data.data_ingesion
    deps:
    - data/raw/Telecom_Churn.csv
    - src/data/data_ingesion.py
    - logger/logger.py
    outs:
    - data/interim/cleaned_data.csv
  feature-eng:
    cmd: python -m src.feature.feature_eng
    deps:
    - data/interim/cleaned_data.csv
    - logger/logger.py
    - src/feature/feature_eng.py
    outs:
    - data/processed/feature_eng_data.csv
  model-building:
    cmd: python -m src.model.model_building
    deps:
    - data/processed/feature_eng_data.csv
    - logger/logger.py
    - src/model/model_building.py
    outs:
    - data/processed/split/x_test.csv
    - data/processed/split/x_train.csv
    - data/processed/split/y_test.csv
    - data/processed/split/y_train.csv
